sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    database: 1
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tP6dXbjYrfKBFoV5rhf
    access-key-secret: cgeZNPVucnstJcibj1JwFJC2ZFNbl6
    bucket-name: web-project-qxp
  wechat:
    appid: wxd8207f02c0cfc238
    secret: 831583d9912f08beca218105b6dfddb7
  baidumap:
    address: 北京市朝阳区新街大道一号楼8层
    ak: ql3yoZ1Jw6quFSLtVWecQUme0Ae5753k
    output: json
    sk: a2exhhptqrxqSepxxsvnFnI2y8PhLHnZ